[workspace]
resolver = "3"
members = ["manager-server","proto", "wasm-bridge", "worker", "worker-bin"]

[profile.wasm-bridge]
inherits = "release"
panic = "abort"
lto = "fat"
codegen-units = 1
incremental = false
debug = "none"
strip = true


[workspace.dependencies]
anyhow = "1.0.100"
