[package]
name = "worker-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
proto = { version = "*", path = "../proto" }
worker = { version = "*", path = "../worker" }
clap = { version = "4.5.53", features = ["derive"] }
anyhow = { workspace = true }
