[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
proto = { version = "*", path = "../proto" }
clap = { version = "4.5.53", features = ["derive"] }
quinn = "0.11.9"
wasmtime = "40.0.0"
anyhow = "1"